# Accessing and Changing elements from rows, colums

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
#get a specific element (python index starts from 0) [row, column]

a[0,2]


3

In [4]:
#get a specific row of elements
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
#get a specific column of elements

In [6]:
a[:,2]

array([ 3, 10])

In [7]:
#get multiple elements
a[1,1:5]

array([ 9, 10, 11, 12])

In [8]:
# changing elemets
a[1,2]=50
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 50 11 12 13 14]]


# 3d arrays

In [9]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
#accessing 3d array from (out to in)
b[1,1,2]

12

In [11]:
b[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [12]:
#Replacing entire sections
b[:,1,:]=[[10,20,30],[40,50,60]]
print(b)

[[[ 1  2  3]
  [10 20 30]]

 [[ 7  8  9]
  [40 50 60]]]


In [13]:
len(b[1,1])

3