# Numpy basics

In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3])
print(a)
a.ndim   #prints dimension of a
a.shape

[1 2 3]


(3,)

In [4]:
b=np.array([[9.0,8.0,7.8],[1,2.1,3.3]])
print(b)
b.shape # prints(row,columns)

[[9.  8.  7.8]
 [1.  2.1 3.3]]


(2, 3)

In [5]:
a.dtype #get data type of array

dtype('int32')

In [6]:
a=np.array([1,2,3], dtype='int16') #reset data type of array
a.dtype #get data type of array, int 16 smaller than int 32


dtype('int16')

In [7]:

a.itemsize #get size of array

2