# Initializing Different Types of Arrays

In [2]:
import numpy as np


#All zeros matrix
A=np.zeros((3,3))
print (A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
#any other number
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [5]:
#random numbers (decimals)
np.random.rand(4,5)    #4 x 5 matrix

array([[0.11606537, 0.85223873, 0.43958428, 0.94153892, 0.71582621],
       [0.49599814, 0.8867685 , 0.30085819, 0.25969831, 0.63257242],
       [0.00616145, 0.98284716, 0.44805494, 0.38985287, 0.91363348],
       [0.33045532, 0.0033548 , 0.18418921, 0.96963174, 0.24778909]])

In [6]:
#random integers with set matrix size

np.random.randint(1,30,size=(3,3)) #1 to 30, matrix 3 x 3

array([[28, 28, 29],
       [ 6, 23,  3],
       [ 4,  7, 11]])

In [7]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#problem 1

output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
b[1,1]=9
print(b)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [11]:
output[1:4,1:4]=b
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
y=np.linspace(2,10,5).astype(int)
y

array([ 2,  4,  6,  8, 10])

In [18]:
y.shape

(5,)

# Copying arrays

In [ ]:
#Error when directly assigning variables

a=np.array([1,2,3])
b=a
b[0]=100
print(a)

In [ ]:
#Solution
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)