# Mathematics

In [23]:
import numpy as np

a=np.array([1,2,3])

a+2


array([3, 4, 5])

In [24]:
a-2


array([-1,  0,  1])

In [25]:
a*2

array([2, 4, 6])

In [26]:
a/2

array([0.5, 1. , 1.5])

In [27]:
a**2


array([1, 4, 9], dtype=int32)

In [28]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [29]:
b=np.array([5,6,7])
a+b

array([ 6,  8, 10])

In [30]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear algebra

In [37]:
a=np.array([1,2,3])   #1 x 3 matrix
b=np.array([[2],[4],[6]]) #3 x 1 matrix

np.matmul(a,b)  #returns matrix multiplication of a x b can use a@b too

array([28])

In [32]:
c=np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
np.linalg.det(c) #determinant of matrix

1.0

In [41]:
d=np.array([[1,2],[3,4]])
e=np.linalg.inv(d)
print(e)

print(e@d)

np.around(e @ d).astype(int) #convert to int first before multiplication, only forms identity after multiplication

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


array([[1, 0],
       [0, 1]])

In [48]:
f=np.array([[5,6],[7,8]])
f


array([[5, 6],
       [7, 8]])

In [47]:
print(f.transpose()) #transpose of matrix

[[5 7]
 [6 8]]


In [42]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [51]:
g=np.array([[1,20,3],[4,5,6]])
np.max(g)

20

In [50]:
np.min(g)

1

In [53]:
np.max(g,axis=1) #max of each row

array([20,  6])

In [54]:
np.max(g,axis=0) #max of each column

array([ 4, 20,  6])

In [55]:
np.sum(g,axis=0)


array([ 5, 25,  9])

In [56]:
np.sum(g,axis=1)

array([24, 15])