In [9]:
import numpy as np

before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
after=before.reshape((4,2)) #reshape matrix to 4 x 2 matrix
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
after=after.reshape((8,1)) #reshape matrix to 8 x 1
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [12]:
v1=np.ones((4,4))
v2=np.full((4,4),5)
np.vstack([v1,v2])  #stack two matrices vertically

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [15]:
c=np.hstack([v1,v2]).astype(int)
c

array([[1, 1, 1, 1, 5, 5, 5, 5],
       [1, 1, 1, 1, 5, 5, 5, 5],
       [1, 1, 1, 1, 5, 5, 5, 5],
       [1, 1, 1, 1, 5, 5, 5, 5]])

In [16]:
np.sum(c, axis=0)

array([ 4,  4,  4,  4, 20, 20, 20, 20])